### ISSUE TITLE
Missing FinalRelert2.csf

### ISSUE THREAD

**Issue by guidebee** [secsome/FinalRelert2#1]
if (LanguageManager::Current.Load("FinalRelert2.csf"))
            {
                if (theApp = new CApp)
                {
                    theApp->Run();
                    delete theApp;
                    theApp = nullptr;
                }
                else
                    ::MessageBox(NULL, "Cannot create CApp!", "Error", MB_OK);
            }
            else
                ::MessageBox(NULL, "Cannot load FinalRelert2.csf!", "Error", MB_OK);

**Comment by secsome** [comment]
This project is still in a very early stage; the `FinalAlert2.csf` is just the editor's language file for now; it will be added to the repository in later builds. So there's no problem about it; comment it out if you still want to run the ||empty|| project. It will just display a lot of `MISSING:TEXT`
